server:
  port: 10086
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hotel_database?useSSL=false
    username: huangjinhui
    password: huangjinhui
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo